name: Unblock Dependencies

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  unblock:
    runs-on: ubuntu-latest
    steps:
      - name: Find and unblock dependent tickets
        uses: actions/github-script@v7
        with:
          script: |
            const closedIssue = context.payload.issue;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            console.log(`Issue #${closedIssue.number} closed. Checking for blocked dependents...`);
            
            // Find all issues with status:blocked label
            const blockedIssues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              labels: 'status:blocked',
              per_page: 100
            });
            
            if (blockedIssues.data.length === 0) {
              console.log('No blocked issues found.');
              return;
            }
            
            for (const issue of blockedIssues.data) {
              // Check if this issue references the closed issue in its body
              const body = issue.body || '';
              const depSection = body.match(/### Dependencies[\s\S]*?(?=###|$)/i);
              if (!depSection) continue;
              
              // Extract all issue refs (#N) from the dependencies section
              const refs = depSection[0].match(/#(\d+)/g);
              if (!refs) continue;
              
              const depNumbers = refs.map(r => parseInt(r.replace('#', '')));
              
              // Check if the closed issue is one of the dependencies
              if (!depNumbers.includes(closedIssue.number)) continue;
              
              console.log(`Issue #${issue.number} depends on #${closedIssue.number}. Checking all deps...`);
              
              // Check if ALL dependencies are now closed
              let allClosed = true;
              for (const depNum of depNumbers) {
                try {
                  const dep = await github.rest.issues.get({
                    owner,
                    repo,
                    issue_number: depNum
                  });
                  if (dep.data.state !== 'closed') {
                    console.log(`  #${depNum} still open — #${issue.number} stays blocked`);
                    allClosed = false;
                    break;
                  }
                } catch (e) {
                  // Cross-repo ref or invalid — skip
                  console.log(`  #${depNum} not found in this repo, skipping`);
                }
              }
              
              if (allClosed) {
                console.log(`All deps closed! Unblocking #${issue.number}`);
                
                // Remove status:blocked, add status:new
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: issue.number,
                  name: 'status:blocked'
                }).catch(() => {});
                
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number: issue.number,
                  labels: ['status:new']
                });
                
                // Add comment for context
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: issue.number,
                  body: `🔓 **Unblocked** — all dependencies resolved (triggered by #${closedIssue.number} closing).\n\nMoving to \`status:new\` for triage.`
                });
              }
            }
